import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        LogEntrar = new javax.swing.JToggleButton();
        LogCancelar = new javax.swing.JToggleButton();
        LogCampLogin = new javax.swing.JTextField();
        LogCampPass = new javax.swing.JPasswordField();
        LogLogin = new javax.swing.JLabel();
        LogSenha = new javax.swing.JLabel();
        LogImg1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LogImg2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        LogEntrar.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        LogEntrar.setText("Entrar");
        LogEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(LogEntrar);
        LogEntrar.setBounds(160, 180, 82, 34);

        LogCancelar.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        LogCancelar.setText("Cancelar");
        LogCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(LogCancelar);
        LogCancelar.setBounds(240, 180, 96, 34);

        LogCampLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogCampLoginActionPerformed(evt);
            }
        });
        getContentPane().add(LogCampLogin);
        LogCampLogin.setBounds(210, 110, 130, 20);
        getContentPane().add(LogCampPass);
        LogCampPass.setBounds(200, 140, 130, 20);

        LogLogin.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        LogLogin.setText("Login:");
        getContentPane().add(LogLogin);
        LogLogin.setBounds(140, 100, 53, 33);

        LogSenha.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        LogSenha.setText("Senha:");
        getContentPane().add(LogSenha);
        LogSenha.setBounds(130, 130, 59, 33);

        LogImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/computer-icon.png"))); // NOI18N
        getContentPane().add(LogImg1);
        LogImg1.setBounds(0, 40, 130, 140);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 0, 0);

        LogImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cinza-3143.jpg"))); // NOI18N
        LogImg2.setText("jLabel5");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ObjectProperty.create(), LogImg2, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        getContentPane().add(LogImg2);
        LogImg2.setBounds(0, 0, 420, 270);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogCampLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogCampLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogCampLoginActionPerformed

    private void LogEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogEntrarActionPerformed
        try{ //tratamento de erros

        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");//Driver JDBC – Fonte de Dados ODBC

        //conecta no BD, as aspas vazias representam o Login: usuário e senha.

        Connection con = DriverManager.getConnection("jdbc:odbc:DB_Teste","","");

        Statement stmt = con.createStatement();       //objeto comdo sql

        int cadMat=Integer.parseInt( LogCampLogin.getText() );

        String cadNome = LogCampLogin.getText();      //obtém nome digitado

        stmt.executeUpdate("insert into TabFicha (Matricula,Nome) values ('" + cadMat + "','" + cadNome +  "')" );

        JOptionPane.showMessageDialog( this, " Dados Salvos! ");

        con.close();  // fecha conexão com BD

      }  catch( SQLException e){ //trata os erros SQL

            JOptionPane.showMessageDialog(this, "Erro Cmdo SQL " + e.getMessage() );

            } catch( ClassNotFoundException e){      //trata erros de conexão

             JOptionPane.showMessageDialog( this, " Driver não encontrado " );

}
    }//GEN-LAST:event_LogEntrarActionPerformed

    private void LogCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LogCampLogin;
    private javax.swing.JPasswordField LogCampPass;
    private javax.swing.JToggleButton LogCancelar;
    private javax.swing.JToggleButton LogEntrar;
    private javax.swing.JLabel LogImg1;
    private javax.swing.JLabel LogImg2;
    private javax.swing.JLabel LogLogin;
    private javax.swing.JLabel LogSenha;
    private javax.swing.JLabel jLabel2;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
