import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        LogEntrar = new javax.swing.JToggleButton();
        LogCancelar = new javax.swing.JToggleButton();
        LogCampLogin = new javax.swing.JTextField();
        LogCampPass = new javax.swing.JPasswordField();
        LogLogin = new javax.swing.JLabel();
        LogSenha = new javax.swing.JLabel();
        LogImg1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LogImg2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        LogEntrar.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        LogEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botoes_Site_5745_Knob_Valid_Green.png"))); // NOI18N
        LogEntrar.setText("Entrar");
        LogEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogEntrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 100, 0, 0);
        getContentPane().add(LogEntrar, gridBagConstraints);

        LogCancelar.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        LogCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botoes_Site_5750_Knob_Cancel.png"))); // NOI18N
        LogCancelar.setText("Cancelar");
        LogCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 10, 0, 0);
        getContentPane().add(LogCancelar, gridBagConstraints);

        LogCampLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogCampLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 124;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 7, 0, 0);
        getContentPane().add(LogCampLogin, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 124;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 0, 0);
        getContentPane().add(LogCampPass, gridBagConstraints);

        LogLogin.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        LogLogin.setText("Login:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(100, 6, 0, 0);
        getContentPane().add(LogLogin, gridBagConstraints);

        LogSenha.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        LogSenha.setText("Senha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 16, 0, 0);
        getContentPane().add(LogSenha, gridBagConstraints);

        LogImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computer-icon.png"))); // NOI18N
        LogImg1.setText("jLabel3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.ipadx = -42;
        gridBagConstraints.ipady = -22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(70, 0, 0, 0);
        getContentPane().add(LogImg1, gridBagConstraints);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jLabel2, gridBagConstraints);

        LogImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinza-3143.jpg"))); // NOI18N
        LogImg2.setText("jLabel5");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ObjectProperty.create(), LogImg2, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 26;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.ipadx = -642;
        gridBagConstraints.ipady = -549;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(LogImg2, gridBagConstraints);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogCampLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogCampLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogCampLoginActionPerformed

    private void LogEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogEntrarActionPerformed
        try{ //tratamento de erros

        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");//Driver JDBC – Fonte de Dados ODBC

        //conecta no BD, as aspas vazias representam o Login: usuário e senha.

        Connection con = DriverManager.getConnection("jdbc:odbc:DB_Teste","","");

        Statement stmt = con.createStatement();       //objeto comdo sql

        int cadMat=Integer.parseInt( LogCampLogin.getText() );

        String cadNome = LogCampLogin.getText();      //obtém nome digitado

        stmt.executeUpdate("insert into TabFicha (Matricula,Nome) values ('" + cadMat + "','" + cadNome +  "')" );

        JOptionPane.showMessageDialog( this, " Dados Salvos! ");

        con.close();  // fecha conexão com BD

      }  catch( SQLException e){ //trata os erros SQL

            JOptionPane.showMessageDialog(this, "Erro Cmdo SQL " + e.getMessage() );

            } catch( ClassNotFoundException e){      //trata erros de conexão

             JOptionPane.showMessageDialog( this, " Driver não encontrado " );

}
    }//GEN-LAST:event_LogEntrarActionPerformed

    private void LogCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LogCampLogin;
    private javax.swing.JPasswordField LogCampPass;
    private javax.swing.JToggleButton LogCancelar;
    private javax.swing.JToggleButton LogEntrar;
    private javax.swing.JLabel LogImg1;
    private javax.swing.JLabel LogImg2;
    private javax.swing.JLabel LogLogin;
    private javax.swing.JLabel LogSenha;
    private javax.swing.JLabel jLabel2;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
